In [1]:
!pip install cmake dlib face_recognition numpy

# Libraries

In [1]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

In [2]:
pwd

'C:\\Users\\amb\\Downloads\\attendance system\\Attendance-with-Face-Recognition'

# Path for test images

In [3]:
path = 'AttendanceImages'
images = []
classNames = []
myList = os.listdir(path)
print(myList)

['Ahmed ibrahim.jpg', 'Elon Musk.jpg', 'Jeff Bezoz.jpg', 'Messi.webp', 'Ryan Reynolds.jpg', 'treka.jpg']


# Extracting names from the List

In [4]:
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['Ahmed ibrahim', 'Elon Musk', 'Jeff Bezoz', 'Messi', 'Ryan Reynolds', 'treka']


# Converting the Images into Encodings

In [6]:
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

# Marking Attendance

In [7]:
def markAttendance(name):
    with open('Attendance.csv','r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dtString}')
        

encodeListKnown = findEncodings(images)
print('Encoding Complete')


Encoding Complete


# Camera  Access and Capturing the Face

In [16]:
cap = cv2.VideoCapture(0)
frame_resizing = 0.25

while True:
    success, img = cap.read()
    imgS = cv2.resize(img, (0, 0), fx=frame_resizing, fy=frame_resizing)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)
 
    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS,facesCurFrame)
 
    for encodeFace,faceLoc in zip(encodesCurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
        print('matches',matches)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)
        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            
            faceLoc = np.array(faceLoc)
            faceLoc = faceLoc / 0.25
            faceLoc=faceLoc.astype(int)
            #y1,x2,y2,x1 = faceLoc # in the other code we risize the face
            #y1, x2, y2, x1 = y1*4,x2*4,y2*4,x1*4
            y1, x2, y2, x1 = faceLoc[0], faceLoc[1], faceLoc[2], faceLoc[3]
         
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendance(name)
 
    cv2.imshow('Webcam',img)
    key = cv2.waitKey(1)
    if key == 27:
        break
cap.release()
cv2.destroyAllWindows()

matches [True, False, False, False, False, False]
[0.46268622 0.85136075 0.89716433 0.70533683 0.79221977 0.66947333]
AHMED IBRAHIM
matches [True, False, False, False, False, False]
[0.47412574 0.90159124 0.83590901 0.77331387 0.84128266 0.74494309]
AHMED IBRAHIM
matches [True, False, False, False, False, False]
[0.44246244 0.77311929 0.88324544 0.68117972 0.7736796  0.64718137]
AHMED IBRAHIM
matches [True, False, False, False, False, False]
[0.52334616 0.73169251 0.83682351 0.69184362 0.81685213 0.71622436]
AHMED IBRAHIM
matches [True, False, False, False, False, False]
[0.36689225 0.85850594 0.8988817  0.74689482 0.80332597 0.70665644]
AHMED IBRAHIM
matches [True, False, False, False, False, False]
[0.43186003 0.85970351 0.93084011 0.75076338 0.83315947 0.76505542]
AHMED IBRAHIM
matches [True, False, False, False, False, False]
[0.40814955 0.86408439 0.90362826 0.7379361  0.83337919 0.75150066]
AHMED IBRAHIM
matches [True, False, False, False, False, False]
[0.40023197 0.84986055 0.9